version: "2.2"

services:
  # Configuration for the EHR service.
  app:
    # Build application using Dockerfile contained in application subfolder
    build: ./application
    # Name image
    image: ethercis-app
    # Map application container port 8080 to Docker port 8080
    ports:
      - "8888:8080"
    # Do not start application container until postgres service is started
    depends_on:
      - postgres
    # Limit memory use
    mem_limit: 1024m

  # Configuration for the postgres service. This service populates the EHR DB.
  postgres:
    # Build database using Dockerfile contained in postgres subfolder
    build: ./postgres
    # Name image
    image: ethercis-db
    # Limit memory use
    mem_limit: 512m
